---
title: "3/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
c("小明今年歲數",25)
```

```{r}
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}
majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
levels(majors10_factor)
```

```{r}
stringInteger <- c(1,2,-11)
class(stringInteger)
stringInteger+2
```

```{r}
studentId <- c(410773002, 410773015)
class(studentId)
as.character(studentId)
```
```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40",
                  tz="Europe/Lisbon")
```

```{r}
with_tz(tpeTime, tzone="UTC")
with_tz(pgTime, tzone="UTC")
```

```{r}
studentTime <- c(
  ymd_hms("2020-03-04T08:19:19Z"),
  ymd_hms("2020-03-11 16:11:43",tz="Asia/Taipei"),
  ymd_hms("2020-03-11 16:11:43",tz="Asia/Taipei")
)
studentTime
```
```{r}
vectorExample<-c(2,6,7)
listExample <-list(2,6,7)

print(vectorExample)
print(listExample)
```

```{r}
c("2020-03-31T13:40:55Z","一芳","2","水果茶")

library(lubridate)
'小明交易' <- list(ymd_hms("2020-03-31T13:40:55Z"),
     "一芳",
     2,
     "水果茶")
print('小明交易')
```

```{r}
c(
  c("108-1", "高級會計學",  "高等統計學"),
  c("108-2","食在拉丁美洲")
)
```
```{r}
`小明108學年課表B`<-list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

